spring:
  application:
    name: ToDoList
  profiles:
    active: dev  # Define o perfil ativo como 'dev' por padrão (pode ser alterado para 'prod' em produção)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true  # Habilita o console H2 em modo desenvolvimento
  jpa:
    hibernate:
      ddl-auto: update  # Cria e atualiza as tabelas automaticamente
      allow_jdbc_metadata_access: false
    show-sql: true      # Mostra as queries SQL no console
